status = [
    "build-library (1.52.1, x86_64-unknown-linux-gnu, false)",
    "build-library (stable, x86_64-unknown-linux-gnu, false)",
    "build-library (beta, x86_64-unknown-linux-gnu, false)",
    "build-library (1.52.1, x86_64-unknown-linux-musl, false)",
    "build-library (1.52.1, x86_64-pc-windows-gnu, true)",
    "build-library (1.52.1, x86_64-unknown-freebsd, true)",
    "build (1.54.0, x86_64-unknown-linux-gnu, false, false)",
    "build (stable, x86_64-unknown-linux-gnu, false, false)",
    "build (beta, x86_64-unknown-linux-gnu, false, false)",
    # "build (stable, x86_64-unknown-freebsd, true, false)",
    "build (stable, x86_64-unknown-linux-musl, false, false)",
    "build (stable, x86_64-pc-windows-gnu, true, false)",
    "integration-test-linux",
    # "integration-test-freebsd",
    "integration-test-windows",
    "rustfmt",
    "clippy",
    "check-license-headers",
    "yamllint",
]
