status = [
    "build (1.40.0, x86_64-unknown-linux-gnu, false, false)",
    "build (stable, x86_64-unknown-linux-gnu, false, false)",
    "build (beta, x86_64-unknown-linux-gnu, false, false)",
    "build (stable, x86_64-unknown-freebsd, true, false)",
    "build (stable, x86_64-unknown-linux-musl, false, false)",
    "build (stable, x86_64-pc-windows-gnu, true, false)",
    "rustfmt",
    "clippy",
    "check-license-headers",
    "yamllint",
]
