name: cargo-audit

on:
  pull_request:
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: cargo audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
