name: CI

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:
    branches:
    - master

jobs:
  check-license-headers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check license headers
      run: |
        ./hack/check-license-headers.sh

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt

    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy

    - name: cargo clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace --lib --bins --tests --all-targets -- -Dwarnings

  yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: ibiqlik/action-yamllint@v1

  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}

    strategy:
      fail-fast: false
      matrix:
        rust:
        - stable
        - beta
        - # MSRV
          1.40.0
        target:
        - "x86_64-unknown-linux-gnu"
        use-cross:
        - false
        continue-on-error:
        - false

        include:
        - rust: stable
          target: "x86_64-unknown-linux-musl"
          use-cross: false
          continue-on-error: false
        - rust: nightly
          target: "x86_64-unknown-linux-gnu"
          use-cross: false
          continue-on-error: true
        - rust: stable
          target: "x86_64-pc-windows-gnu"
          use-cross: true
          continue-on-error: false
        - rust: stable
          target: "x86_64-unknown-freebsd"
          use-cross: true
          continue-on-error: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        override: true

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: ${{ matrix.use-cross }}
        args: --target ${{ matrix.target }}
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture
      env:
        TARGET: ${{ matrix.target }}
